---
name: tests

on:  # yamllint disable-line rule:truthy
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    cookie:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              if: ${{ always() }}
            - name: Run tox based tests
              uses: fedora-python/tox-github-action@v0.4
              with:
                  tox_env: ${{ matrix.tox_env }}
              if: ${{ always() }}
            - name: Coveralls Parallel
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.github_token }}
                flag-name: run-${{ matrix.tox_env }}
              parallel: true
        strategy:
            matrix:
                tox_env: [py36, py37, py38, py39]
